### ISSUE TITLE
toDo

### ISSUE THREAD

**Issue by enukidze** [enukidze/Svetiskhoveli#1]
- [ ] Font
- [ ] text to card
- [ ] delete datgui / helper
- [ ] rotating cube(wireframe)

**optional** :

- [ ] checking model in blender  / exporting as texture
